# グラフ全体の設定
canvas:

  figsize:
    width: 20 #[cm]
    height: 10 #[cm]

  fontstyle: 
    family: "serif" #Arial, serif

  title: #グラフタイトル
    text: "title"
    fontsize: 30

  label: #xy軸のラベル
    xlabel: xlabel
    ylabel: ylabel
    fontsize: 18

  ticks: # 目盛りの幅. limitにnullが指定されると無視される

    visible: 
      xlabel: false
      ylabel: false

    xwidth: 5 
    xbias: 0 #x軸の実際のgrid線のbias
    xlabel_bias: 0 #x軸のラベルのbias(=描画される数字のbias)

    ywidth: 10
    ybias: 0.0 #y軸の実際のgrid線のbias
    ylabel_bias: 0 #y軸のラベルのbias(=描画される数字のbias)

    fontsize: 12
    num_decimal_places: 1 #小数点以下の桁数


  legend: #凡例のフォントサイズ
    fontsize: 12

  grid:
    visible: true
    alpha: 0.5

  limit: #xy軸の範囲
    xmin: 0
    xmax: null
    ymin: 0
    ymax: null

  axscale: #xy軸のスケール. 対数軸か否か
    x: linear #linear, log
    y: linear #linear, log

  margin: #グラフの余白差分. グラフの余白がデフォルトからどれくらい変更されるか
    left: 0.5 #[cm]
    right: -1.3 #[cm]
    top: -0.5 #[cm]
    bottom: -0.5 #[cm]