# グラフ全体の設定
canvas:

  figsize:
    width: 20 #[cm]
    height: 10 #[cm]

  fontstyle: 
    family: "serif" #Arial, serif

  title: #グラフタイトル
    text: "title"
    fontsize: 30

  label: #xy軸のラベル
    xlabel: xlabel
    ylabel: ylabel
    fontsize: 18

  ticks: # 目盛りの幅. limitにnullが指定されると無視される
    xwidth: 5 
    ywidth: 10
    fontsize: 12

  legend: #凡例のフォントサイズ
    fontsize: 12

  grid:
    visible: true
    alpha: 0.5

  limit: #xy軸の範囲
    xmin: 0
    xmax: null
    ymin: 0
    ymax: null
