# グラフ1つ分の設定
heatmap:
  csvpath: C:\Users\3meko\Dev\my_tools\RealtimeGraphViewer\test\testdata2.csv

  label: #凡例のラベル
    text: "heatmap1" 
    fontsize: 16

  valuecol: ycol #ヒートマップの値そのものの列名. indexでもOK
  y: 1 #ヒートマップを描画するy軸の位置

  cmap: viridis #カラーマップ

  boundary: #ヒートマップの境界線
    color: white
    linewidth: 2
